name: PR Tests

on:
  pull_request:
    branches:
    - master

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 rhalphalib --count --show-source --statistics

  test:
    name: Run pytest (Python ${{ matrix.python-version }}, ROOT ${{ matrix.root-version }})
    needs: linter
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: true
      matrix:
        python-version: [3.7]
        root-version: [6.16, 6.22]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: condaenv
    - name: Install ROOT ${{ matrix.root-version }}
      shell: bash -l {0}
      run: |
        mamba install -c conda-forge numpy scipy nomkl root==${{ matrix.root-version }}
    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pip install pytest
        pytest tests
